# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-29 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='invites_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invite',
            name='send_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
